#!/usr/bin/env python3.14
"""
Guided setup for the applicant's personal data used in block_and_fill (auto-fill)
mode. Writes/updates applicant.env next to this script.

Run:  python3.14 setup_applicant.py

Nothing here talks to the network; it only asks questions and writes a local
file. Re-run any time to edit — existing values are shown as defaults and kept
if you just press Enter. Leave a field blank if it doesn't apply.
"""
from __future__ import annotations

import os
import sys

# Windows consoles default to cp1252, which can't encode Polish labels (ę, ł...).
# Force UTF-8 on the streams so the prompts don't crash / mojibake.
for _stream in (sys.stdout, sys.stdin, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
    except Exception:
        pass

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
APPLICANT_ENV_PATH = os.path.join(BASE_DIR, "applicant.env")

# (env_key, question shown to the user, optional note)
FIELDS = [
    ("FORM_IMIE",            "Imię (first name)", ""),
    ("FORM_NAZWISKO",        "Nazwisko (surname)", ""),
    ("FORM_DATA_URODZENIA",  "Data urodzenia (date of birth)", "e.g. 1965-04-23"),
    ("FORM_OBYWATELSTWO",    "Obywatelstwo (citizenship)", "e.g. Ukraina"),
    ("FORM_EMAIL",           "Email", "REQUIRED — the office sends a confirmation link here"),
    ("FORM_TELEFON",         "Telefon (phone)", "e.g. +48123456789"),
    ("FORM_NUMER_SPRAWY",    "Numer sprawy (case number)", "if her case has one"),
    ("FORM_PESEL",           "PESEL", "if she has one"),
    ("FORM_NUMER_DOKUMENTU", "Numer dokumentu (document number)", "if applicable"),
    ("FORM_NUMER_PASZPORTU", "Numer paszportu (passport number)", "if applicable"),
]


def read_existing() -> dict:
    """Parse the current applicant.env (simple KEY=VALUE lines) if it exists."""
    values = {}
    if not os.path.exists(APPLICANT_ENV_PATH):
        return values
    with open(APPLICANT_ENV_PATH, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, val = line.partition("=")
            values[key.strip()] = val.strip()
    return values


def prompt(question: str, note: str, current: str) -> str:
    hint = f" [{note}]" if note else ""
    if current:
        shown = f" (current: {current!r}, Enter to keep)"
    else:
        shown = " (Enter to skip)"
    try:
        answer = input(f"  {question}{hint}{shown}: ").strip()
    except EOFError:
        return current
    return current if answer == "" else answer


def write_env(values: dict) -> None:
    lines = [
        "# Applicant personal data for auto-fill (MODE=block_and_fill).",
        "# Generated by setup_applicant.py — re-run that script to edit safely.",
        "# Keep this file private; it holds one person's personal details.",
        "",
    ]
    for key, _, _ in FIELDS:
        lines.append(f"{key}={values.get(key, '')}")
    with open(APPLICANT_ENV_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def main() -> int:
    print("=" * 68)
    print(" Applicant setup — personal data for auto-filling the reservation")
    print(" form (used only when MODE=block_and_fill).")
    print(" Press Enter to keep the current value / skip an inapplicable field.")
    print("=" * 68)

    existing = read_existing()
    values = {}
    for key, question, note in FIELDS:
        values[key] = prompt(question, note, existing.get(key, ""))

    if not values.get("FORM_EMAIL"):
        print(
            "\n  ! Warning: no email set. The office emails a confirmation link "
            "that must be clicked to finalize the booking — without an email the "
            "auto-fill can't complete.\n"
        )

    write_env(values)
    filled = sum(1 for v in values.values() if v)
    print(f"\nSaved {filled} field(s) to {APPLICANT_ENV_PATH}")
    print("The bot loads this automatically on next start. Done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
